kind: Deployment
apiVersion: apps/v1
metadata:
  name: myphpapp
  labels:
    app: myphpapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myphpapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myphpapp
    spec:
      containers:
        - name: myphpapp
          image: mytestk8s.azurecr.io/myphpapp:10
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
          env:
            - name: ConnectionString__ApplicationConnectionString
              valueFrom:
               secretKeyRef:
                 name: puja-sql-db-creds
                 key: connection-string
            - name: ConnectionString__IdentityConnectionString
              valueFrom:
               secretKeyRef:
                 name: puja-sql-db-creds
                 key: connection-string
            - name: ConnectionString__HealthCheckConnectionString
              valueFrom:
               secretKeyRef:
                 name: puja-sql-db-creds
                 key: connection-string


            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---
apiVersion: v1
kind: Service
metadata:
  name: myphpapp-service
spec:
  type: LoadBalancer
  selector:
    app: myphpapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
                                                                                                                                                                     61,20         Bot


